### ISSUE TITLE
if правильно, но недоделано.

### ISSUE THREAD

**Issue by denis-trofimov** [klonkenni/Lesson2#2]
https://github.com/klonkenni/Lesson2/blob/4e2eead7bc68d890c50f3a74fbe1d9df48d964a5/Lesson2/if/Task1.py#L16

> Вызвать функцию, передав ей возраст пользователя и положить результат работы функции в преременную
Вывести содержимое переменной на экран

**Comment by klonkenni** [comment]
Поправил
