### ISSUE TITLE
Задание можно понять иначе. Как понимать условие задачи?

### ISSUE THREAD

**Issue by denis-trofimov** [klonkenni/Lesson2#3]
https://github.com/klonkenni/Lesson2/blob/4e2eead7bc68d890c50f3a74fbe1d9df48d964a5/Lesson2/if/Task2.py#L11

Как понимать условие задачи?
Считаем их написал бизнесмен, не программист. То есть, это не алгоритм. 
Подсказка. Тогда "Если строки разные и вторая строка 'learn', возвращает 3 ", значит 'learn' это стоп-слово, и при нем должно быть 3. не зависимо от того, какая из двух длиннее.

**Comment by klonkenni** [comment]
Поправил
